### ISSUE TITLE
Plugin appears to only gather metrics on top-level jobs

### ISSUE THREAD

**Issue by rbutcher** [signalfx/collectd-jenkins#21]
### Description
I have multiple instances of Jenkins running in Kubernetes for which I have configured the Smart Agent to collect metrics. Upon completing configuration I was looking at the dashboards surfaced through SignalFX for Jenkins and noticed the "Job Failure Rate" and "Top 5 Failed Jobs" charts not populating. Creating a chart using the "gauge.jenkins.job.duration" yields an empty chart (no values). It does not appear that the plugin is collecting any information on job duration. Peeking into the code it does not look like the plugin will recursively search folders for build information. Everything else appears to be working as configured.

### Background
I am fairly sure this issue is not directly related to our Jenkins configuration. I am providing this information in case there is something I missed and to give a bit of context.

We are forced to use folders due to the plugin we use (Bitbucket Branch Source) to discover jobs from an on premise Bitbucket system. This system creates a folder for the Bitbucket project and creates a sub-folder per repository in that project.

An example job URL looks something like:
`https://<internal-url>/job/DevOps/job/builddirector/job/master/`

This build is located in:
DevOps > BuildDirector > Master

Smart Agent Configuration Snippet
``` yaml
- type: collectd/jenkins
  metricsKey: <metrics-key-omitted>
  username: <user-name-omitted>
  apiToken: <api-token-omitted>
  enhancedMetrics: true
  discoveryRule: 'kubernetes_pod_name =~ "devops-" && container_image =~ "jenkins" && port == 8080'
```

### Steps to Recreate

- Create a folder in Jenkins.
- Inside that folder create a job.
- Configure Smart Agent to collect metrics from Jenkins instance.
- Observe missing job metrics.
